name: Build u-boot for RK356x
run-name: u-boot ${{ inputs.uboot_ref }} for RK356x
on:
  workflow_dispatch:
    inputs:
      uboot_ref:
        description: u-boot ref
        required: true
        default: master
        type: string
      rkbin_ref:
        description: rkbin ref
        required: true
        default: master
        type: string
      tf-a_ref:
        description: tf-a ref
        required: true
        default: main
        type: string

jobs:
  build:
    name: ${{ matrix.boards.name }}
    runs-on: ubuntu-24.04-arm
    strategy:
      fail-fast: false
      matrix:
        boards:
          [
            {
              "name": "rk3566-anbernic-rgxx3",
              "config": "anbernic-rgxx3-rk3566_defconfig",
              "variant": "RK3566",
            },
            {
              "name": "rk3566-orangepi-3b",
              "config": "orangepi-3b-rk3566_defconfig",
              "variant": "RK3566",
            },
            {
              "name": "rk3566-pinetab2",
              "config": "pinetab2-rk3566_defconfig",
              "variant": "RK3566",
            },
            {
              "name": "rk3566-powkiddy-x55",
              "config": "powkiddy-x55-rk3566_defconfig",
              "variant": "RK3566",
            },
            {
              "name": "rk3566-quartz64-a",
              "config": "quartz64-a-rk3566_defconfig",
              "variant": "RK3566",
            },
            {
              "name": "rk3566-quartz64-b",
              "config": "quartz64-b-rk3566_defconfig",
              "variant": "RK3566",
            },
            {
              "name": "rk3566-radxa-cm3-io",
              "config": "radxa-cm3-io-rk3566_defconfig",
              "variant": "RK3566",
            },
            {
              "name": "rk3566-radxa-zero-3",
              "config": "radxa-zero-3-rk3566_defconfig",
              "variant": "RK3566",
            },
            {
              "name": "rk3566-rock-3c",
              "config": "rock-3c-rk3566_defconfig",
              "variant": "RK3566",
            },
            {
              "name": "rk3566-soquartz-blade",
              "config": "soquartz-blade-rk3566_defconfig",
              "variant": "RK3566",
            },
            {
              "name": "rk3566-soquartz-cm4",
              "config": "soquartz-cm4-rk3566_defconfig",
              "variant": "RK3566",
            },
            {
              "name": "rk3566-soquartz-model-a",
              "config": "soquartz-model-a-rk3566_defconfig",
              "variant": "RK3566",
            },
            {
              "name": "rk3568-bpi-r2-pro",
              "config": "bpi-r2-pro-rk3568_defconfig",
              "variant": "RK3568",
            },
            {
              "name": "rk3568-evb",
              "config": "evb-rk3568_defconfig",
              "variant": "RK3568",
            },
            {
              "name": "rk3568-generic-rk3568",
              "config": "generic-rk3568_defconfig",
              "variant": "RK3568",
            },
            {
              "name": "rk3568-lubancat-2",
              "config": "lubancat-2-rk3568_defconfig",
              "variant": "RK3568",
            },
            {
              "name": "rk3568-nanopi-r5c",
              "config": "nanopi-r5c-rk3568_defconfig",
              "variant": "RK3568",
            },
            {
              "name": "rk3568-nanopi-r5s",
              "config": "nanopi-r5s-rk3568_defconfig",
              "variant": "RK3568",
            },
            {
              "name": "rk3568-odroid-m1",
              "config": "odroid-m1-rk3568_defconfig",
              "variant": "RK3568",
            },
            {
              "name": "rk3568-radxa-e25",
              "config": "radxa-e25-rk3568_defconfig",
              "variant": "RK3568",
              "baudrate": "115200",
            },
            {
              "name": "rk3568-rock-3a",
              "config": "rock-3a-rk3568_defconfig",
              "variant": "RK3568",
            },
            {
              "name": "rk3568-rock-3b",
              "config": "rock-3b-rk3568_defconfig",
              "variant": "RK3568",
            },
          ]

    steps:
      - name: Toolchain
        run: |
          sudo apt update
          sudo apt install gcc python3-pyelftools confget libgnutls28-dev uuid-dev
          gcc --version

      - name: Checkout rkbin - ${{ inputs.rkbin_ref }}
        uses: actions/checkout@v4
        with:
          repository: rockchip-linux/rkbin
          ref: ${{ inputs.rkbin_ref }}
          path: rkbin

      - name: Checkout ARM Trusted Firmware-A - ${{ inputs.tf-a_ref }}
        uses: actions/checkout@v4
        with:
          repository: TrustedFirmware-A/trusted-firmware-a
          ref: ${{ inputs.tf-a_ref }}
          path: trusted-firmware-a

      - name: Checkout u-boot - ${{ inputs.uboot_ref }}
        uses: actions/checkout@v4
        with:
          repository: u-boot/u-boot
          ref: ${{ inputs.uboot_ref }}
          path: u-boot

      - name: Build Trusted Firmware-A - ${{ matrix.boards.variant }}
        working-directory: ./trusted-firmware-a/
        run: |
          make PLAT=rk3568 -j$(nproc) bl31
          ls -l build/rk3568/release/bl31/bl31.elf

      # https://github.com/rockchip-linux/rkbin/blob/master/RKBOOT/RK3568MINIALL.ini
      # https://github.com/rockchip-linux/rkbin/blob/master/tools/ddrbin_tool_user_guide.txt
      # https://devel.ringlet.net/textproc/confget/
      - name: Build u-boot - ${{ matrix.boards.config }}
        run: |
          set -ex
          DDRBIN=$(confget -f rkbin/RKBOOT/${{ matrix.boards.variant }}MINIALL.ini -s LOADER_OPTION FlashData)

          #if test -n "${{ matrix.boards.baudrate }}"; then
              sed -i 's/uart baudrate=.*/uart baudrate=${{ matrix.boards.baudrate }}/' rkbin/tools/ddrbin_param.txt
              sed -i 's/link_ecc_en=.*/link_ecc_en=1/' rkbin/tools/ddrbin_param.txt
              SOC=$(echo "${{ matrix.boards.variant }}" | tr '[:upper:]' '[:lower:]')
              python3 rkbin/tools/ddrbin_tool.py $SOC rkbin/tools/ddrbin_param.txt rkbin/$DDRBIN
          #fi

          export ROCKCHIP_TPL=../rkbin/$DDRBIN
          export BL31=../trusted-firmware-a/build/rk3568/release/bl31/bl31.elf
          cd u-boot
          make mrproper
          make ${{ matrix.boards.config }}
          make KCFLAGS="-Werror" CROSS_COMPILE=aarch64-linux-gnu- -j$(nproc)
          tools/mkimage -l u-boot.itb
          sha256sum idbloader.img u-boot.itb u-boot-rockchip.bin $(test -f u-boot-rockchip-spi.bin && echo u-boot-rockchip-spi.bin) > sha256sums.txt 2>/dev/null

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.boards.name }}
          path: |
            u-boot/idbloader.img
            u-boot/u-boot.itb
            u-boot/u-boot-rockchip.bin
            u-boot/u-boot-rockchip-spi.bin
            u-boot/sha256sums.txt
