name: Build u-boot for RK356x
run-name: u-boot ${{ inputs.uboot_ref }} and TF-A ${{ inputs.tf-a_ref }} for RK356x
on:
  workflow_dispatch:
    inputs:
      uboot_ref:
        description: u-boot ref
        required: true
        default: master
        type: string
      tf-a_ref:
        description: tf-a ref
        required: true
        default: main
        type: string

jobs:
  build:
    name: ${{ matrix.boards.name }}
    # https://github.com/actions/partner-runner-images
    runs-on: ubuntu-24.04-arm
    strategy:
      fail-fast: false
      matrix:
        boards:
          [
            {
              "name": "rk3568-odroid-m1",
              "config": "odroid-m1-rk3568_defconfig",
              "variant": "RK3568",
            },
          ]

    steps:
      - name: Toolchain
        run: |
          sudo apt update
          sudo apt install gcc python3-pyelftools confget libgnutls28-dev uuid-dev
          gcc --version

      - name: Checkout rkbin
        uses: actions/checkout@v6
        with:
          repository: rockchip-linux/rkbin
          ref: master
          path: rkbin
          fetch-depth: 1

      # https://github.com/TrustedFirmware-A/trusted-firmware-a/tags
      - name: Checkout ARM Trusted Firmware-A - ${{ inputs.tf-a_ref }}
        uses: actions/checkout@v6
        with:
          repository: TrustedFirmware-A/trusted-firmware-a
          ref: ${{ inputs.tf-a_ref }}
          path: trusted-firmware-a
          submodules: recursive

      # https://github.com/u-boot/u-boot/tags
      - name: Checkout u-boot - ${{ inputs.uboot_ref }}
        uses: actions/checkout@v6
        with:
          repository: u-boot/u-boot
          ref: ${{ inputs.uboot_ref }}
          path: u-boot

      - name: Build Trusted Firmware-A - ${{ matrix.boards.variant }}
        working-directory: ./trusted-firmware-a/
        run: |
          make PLAT=rk3568 -j$(nproc) bl31
          ls -l build/rk3568/release/bl31/bl31.elf

      # https://github.com/rockchip-linux/rkbin/blob/master/RKBOOT/RK3568MINIALL.ini
      # https://github.com/rockchip-linux/rkbin/blob/master/tools/ddrbin_tool_user_guide.txt
      # https://devel.ringlet.net/textproc/confget/
      - name: Build u-boot - ${{ matrix.boards.config }}
        run: |
          set -xeuo pipefail
          DDRBIN=$(confget -f rkbin/RKBOOT/${{ matrix.boards.variant }}MINIALL.ini -s LOADER_OPTION FlashData)

          #if test -n "${{ matrix.boards.baudrate }}"; then
              sed -i 's/uart baudrate=.*/uart baudrate=${{ matrix.boards.baudrate }}/' rkbin/tools/ddrbin_param.txt
              sed -i 's/link_ecc_en=.*/link_ecc_en=1/' rkbin/tools/ddrbin_param.txt
              sed -i 's/dis_train_print=.*/dis_train_print=1/' rkbin/tools/ddrbin_param.txt
              SOC=$(echo "${{ matrix.boards.variant }}" | tr '[:upper:]' '[:lower:]')
              python3 rkbin/tools/ddrbin_tool.py $SOC rkbin/tools/ddrbin_param.txt rkbin/$DDRBIN
          #fi

          export ROCKCHIP_TPL=../rkbin/$DDRBIN
          export BL31=../trusted-firmware-a/build/rk3568/release/bl31/bl31.elf
          cd u-boot

          curl https://github.com/torvalds/linux/commit/5918bf2a17f4689abfb94d341c5240088f8bd16e.patch | \
              git apply -p5 --directory=dts/upstream/src/arm64/
          git --no-pager diff

          make mrproper
          make ${{ matrix.boards.config }}
          make KCFLAGS="-Werror" -j$(nproc)
          tools/mkimage -l u-boot.itb
          sha256sum idbloader.img u-boot.itb u-boot-rockchip.bin $(test -f u-boot-rockchip-spi.bin && echo u-boot-rockchip-spi.bin) > sha256sums.txt 2>/dev/null

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.boards.name }}
          path: |
            u-boot/idbloader.img
            u-boot/u-boot.itb
            u-boot/u-boot-rockchip.bin
            u-boot/u-boot-rockchip-spi.bin
            u-boot/sha256sums.txt
